/* main.c */
#include <stdio.h>
#include "parser.tab.h" // Include the header generated by Bison

extern int yyparse();
extern int result;

int main() {
    printf("Enter an arithmetic expression (Ctrl+D to exit):\n");
    while (yyparse() == 0);
    printf("Final Result: %d\n", result);
    return 0;
}

void yyerror(const char *s) {
    fprintf(stderr, "Error: %s\n", s);
}